---
fixtures:
  repositories:
    stdlib:
      ref: "4.12.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    apt:
      ref: "2.2.2"
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
    docker:
      ref: "v5.3.0"
      repo: "https://github.com/garethr/garethr-docker"
    vision_docker:
      ref: "production"
      repo: "https://github.com/vision-it/vision-docker"

  symlinks:
    vision_freeipa: '#{source_dir}'
