---
fixtures:
  repositories:
    stdlib:
      ref: "v6.2.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    docker:
      ref: "v3.9.1"
      repo: "https://github.com/puppetlabs/puppetlabs-docker"
    apt:
      ref: "v7.1.0"
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
    vision_docker:
      ref: "production"
      repo: "https://github.com/vision-it/vision-docker"

  symlinks:
    vision_freeipa: '#{source_dir}'
